# Generated by Django 4.2.1 on 2023-06-05 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('zip', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(99999)], verbose_name='Индекс')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('state', models.CharField(max_length=30, verbose_name='Штат')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Вес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='cargo.location', verbose_name='Локация доставки')),
                ('pick_up', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_ups', to='cargo.location', verbose_name='Локация отправки')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=5, unique=True, verbose_name='Номер')),
                ('carrying', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъемность')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cargo.location', verbose_name='Текущая локация')),
            ],
        ),
    ]
